### ISSUE TITLE
Do we have any lib compiled for `arm64`?

### ISSUE THREAD

**Issue by jaku-jaku** [RobotnikAutomation/robotnik_base_hw#10]
Hi RobotnikAutomation,

I am wondering if there is any lib released for arm64 platform, I need to integrate the system onto Jetson platform.

Best
jack

**Comment by RomanRobotnik** [comment]
Hi Jack,

Currently there isn't a version for arm64 platform, sorry.

Román

**Comment by jaku-jaku** [comment]
I see, thanks for the quick reply. I will work around the design then.
