### ISSUE TITLE
Published MotorStatus is incomplete in regards to robotnik_msgs

### ISSUE THREAD

**Issue by ChrisSchulte** [RobotnikAutomation/robotnik_base_hw#2]
Calling the controllerStatusPublishing() method of the robotnik_base_hw_lib works correctly but the md5 is incorrect in regards to the one of RobotnikMotosStatus of the robotnik_msgs. 
Removing from robotnik_msgs the last two added variables of message MotorStatus.msg (aka float32 averagecurrent and float32[] analoginputs) corrects the md5 incoherence and allows the topic to be echoed correctly.
As the robotnik_base_hw_lib is not public may it be possible to recompile the library with the new MotorStatus.msg in a new commit ?

Thanks,

Christian

**Comment by RomanRobotnik** [comment]
Hi Christian, 

Thank you for reporting the issue. We'll fix it soon. In the meantime you could try working with robotnik_msgs tag kinetic-0.2.3 or with the rosdistro package.

Regards,

Román

**Comment by marbosjo** [comment]
Built against last version of robotnik_msgs (0.2.4). You can install it from sources or wait for the build farm.
