### ISSUE TITLE
melodic branch

### ISSUE THREAD

**Issue by ferdinandyb** [RobotnikAutomation/robotnik_base_hw#5]
Are there plans to move this to melodic? I would like to use the simulator for RB-1 on melodic, and everything can be built as far as I can see, only the `lib/ros-kinetic-robotnik-base-hw-lib` is causing problems.

**Comment by RomanRobotnik** [comment]
Hi, we plan to migrate the robot controllers and simulation packages. Hopefully it will be ready by June at the latest.

**Comment by ferdinandyb** [comment]
Great news, thanks!

**Comment by jmoras** [comment]
Hi Roman,
Do you have any new concerning the migration to melodic ?

**Comment by RomanRobotnik** [comment]
Hi!

We are working on it, not as fast as we wanted, but making some progress. 

We started with the rb1_base migration (simulation and common packages) and now we want to migrate the hardware components.

Hopefully we can have it during this month.

Regards,

**Comment by smhaller** [comment]
Are there any news?

**Comment by M-Redel** [comment]
Hello have you already migrated robonik-base-hw-lib?

**Comment by gramss** [comment]
Hey,
are there any news..?
Kind regards
